'use strict'
var terms={};
terms.queries = [
{query:'orencia'},
{query:'remicaide'},
{query:'simponi'},
{query:'cimzia'},
{query:'enbrel'},
{query:'humira'},
{query:'xeljanz'},
{query:'\\"#ra\\"'},
{query:'rituximab'},
{query:'actemra'},
{query:'creakychats'},
{query:'rheumatoid'},
{query:'psoriasis'},
{query:'arthritis365'},
{query:'arthritistalk'},

{query:'tocilizumab'},
{query:'methotrexate'},
{query:'mtx'},
{query:'rituximab'},
{query:'abatacept'},
{query:'golimumab'},
{query:'certolizumab'},
{query:'infliximab'},
{query:'Humera'},
{query:'Adalimumab'},
{query:'Adlimumab'},
{query:'Enbril'},
{query:'Eanercept'},
{query:'Etanercept'},
{query:'XEJLANZ'},
{query:'ZELJANZ'},
{query:'Tofacitinib'},
{query:'Tofa'},
{query:'rheum'},
{query:'psoriaticarthritis'},
{query:'rheumatoidarthritis'},
{query:'arthritis'},
{query:'osteoarthritis'},

{query:'ACR15'},
{query:'ACR16'},
{query:'arthritis365'},
{query:'ArthritisTalk'},
{query:'ArthritisReumatoide'},
{query:'EULAR15'},
{query:'EULAR2012'},
{query:'EULAR2014'},
{query:'EULAR2015'},
{query:'EULAR2016'},
{query:'ISR2012'},
{query:'painspot'},
{query:'panlar2015'},
{query:'Rheum'},
{query:'Rheum2016'},
{query:'Rheum2017'},
{query:'RheumatoidArthritis'},
{query:'RheumChat'},
{query:'rheumedu'},
{query:'SimposioAR'},
{query:'SOTASpondylitis'},
{query:'spoonies'},
{query:'TeamSpondy'},
{query:'WomeninRheum'},

{query:'creakyjoints'},
{query:'acrheum'},
{query:'rheumaarthrits'},
{query:'carvicab'},
{query:'artricenter'},
{query:'eular_org'},
{query:'eular_press'},
{query:'spondylitis'},
{query:'abbvie'},
{query:'rheumatologyuk'},
{query:'drailyntan'},
{query:'doctorakerkar'},
{query:'panlarleague'},
{query:'rawarrior'},
{query:'_connectedcare'}
];

module.exports = terms;
